### ISSUE TITLE
APPLICATION FAILED TO START

### ISSUE THREAD

**Issue by denizcoskun** [apereo/cas-gradle-overlay-template#3]
I clean and build application. After that i ran command this gradlew bootRun (or java -jar cas/build/libs/cas.war). It throw an exception "Caused by: java.io.FileNotFoundException: \etc\cas\thekeystore". I think it must be initialized for first time with no ssl certificate and https security. Already cas application throws an exception for ssl security.

**Comment by mmoayyed** [comment]
See Readme for more info

**Comment by denizcoskun** [comment]
I read info. And i ran command step step. But it is not working. It always throw an exception "Caused by: java.io.FileNotFoundException: \etc\cas\thekeystore". I created a keystore and pasted it under \etc\cas\ folder.

**Comment by denizcoskun** [comment]
I solved this. I copied etc file to C:\ directory. Because of cas searchs at root directory. On windows, root directory is c:\ . Could you change properties file or readme for windows configurations.

**Comment by mmoayyed** [comment]
I cannot. Instead, please w submit a pull request with this change you have in mind. Thanks
