### ISSUE TITLE
Update 5.0.2 to Spring boot 1.4.3

### ISSUE THREAD

**Issue by mrcasablr** [apereo/cas-gradle-overlay-template#8]
Spring boot 1.4.3 is GA and has many fixes - https://github.com/spring-projects/spring-boot/milestone/75?closed=1

 A quick check by bumping up to 1.4.3 in gradle properties seem to work well for CAS 5.0.1

**Comment by mmoayyed** [comment]
Move the issue over to CAS.

**Comment by mmoayyed** [comment]
PS When the change is in place, the overlay will be auto-updated when CAS is released.

**Comment by mmoayyed** [comment]
Forgot to mention that you need to make sure you are not running with duplicate JARs. A quick check generally is not enough.If you wish to use 1.4.3 you might as well bump to 5.1.
